"""add encounter number to audit log

Revision ID: 0051b818835b
Revises: 071951c50951
Create Date: 2026-04-27 14:27:53.795219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0051b818835b'
down_revision: Union[str, Sequence[str], None] = '071951c50951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('audit_log', sa.Column('openemr_encounter_number', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('audit_log', 'openemr_encounter_number')
    # ### end Alembic commands ###
