"""add demo patient contact overrides to zoom_accounts

Revision ID: 071951c50951
Revises: 21edaf7095b0
Create Date: 2026-04-21 19:40:39.229729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071951c50951'
down_revision: Union[str, Sequence[str], None] = '21edaf7095b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('zoom_accounts', sa.Column('demo_patient_email_override', sa.String(length=256), nullable=True))
    op.add_column('zoom_accounts', sa.Column('demo_patient_phone_override', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoom_accounts', 'demo_patient_phone_override')
    op.drop_column('zoom_accounts', 'demo_patient_email_override')
    # ### end Alembic commands ###
