"""add meeting_started_at to meeting_records

Revision ID: 18c6821766b3
Revises: 585c85c5c79c
Create Date: 2026-05-04 12:06:49.043725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c6821766b3'
down_revision: Union[str, Sequence[str], None] = '585c85c5c79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_records', sa.Column('meeting_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_zoom_accounts_tenant_id'), 'zoom_accounts', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoom_accounts_tenant_id'), table_name='zoom_accounts')
    op.drop_column('meeting_records', 'meeting_started_at')
    # ### end Alembic commands ###
