"""add meeting_patients and updated meeting_records

Revision ID: 41740385eb41
Revises: a1b2c3d4e5f6
Create Date: 2026-04-19 16:43:29.564423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41740385eb41'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_records', sa.Column('zoom_start_url', sa.String(length=1024), nullable=True))
    op.add_column('meeting_records', sa.Column('zoom_join_url', sa.String(length=1024), nullable=True))
    op.add_column('meeting_records', sa.Column('alternative_host_email', sa.String(length=256), nullable=True))
    op.add_column('meeting_records', sa.Column('openemr_appt_status', sa.String(length=16), nullable=True))
    op.drop_column('meeting_records', 'openemr_patient_id')
    op.drop_column('meeting_records', 'zoom_meeting_url')
    op.add_column('provider_mappings', sa.Column('default_alternative_host_email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_mappings', 'default_alternative_host_email')
    op.add_column('meeting_records', sa.Column('zoom_meeting_url', sa.VARCHAR(length=512), nullable=True))
    op.add_column('meeting_records', sa.Column('openemr_patient_id', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('meeting_records', 'openemr_appt_status')
    op.drop_column('meeting_records', 'alternative_host_email')
    op.drop_column('meeting_records', 'zoom_join_url')
    op.drop_column('meeting_records', 'zoom_start_url')
    # ### end Alembic commands ###
