"""add ehr auth fields to zoom accounts

Revision ID: 585c85c5c79c
Revises: d7de11bd0c97
Create Date: 2026-04-30 20:36:34.505034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585c85c5c79c'
down_revision: Union[str, Sequence[str], None] = 'd7de11bd0c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoom_accounts', sa.Column('tenant_id', sa.String(length=10), nullable=True))
    op.add_column('zoom_accounts', sa.Column('ehr_context_username', sa.String(length=128), nullable=True))
    op.add_column('zoom_accounts', sa.Column('ehr_context_password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoom_accounts', 'ehr_context_password_hash')
    op.drop_column('zoom_accounts', 'ehr_context_username')
    op.drop_column('zoom_accounts', 'tenant_id')
    # ### end Alembic commands ###
