"""current schema with string primary keys

Revision ID: 5ecd2a942ca3
Revises: 0d3e2936f4b1
Create Date: 2026-04-28 15:09:44.396447

"""
import sqlalchemy_utils
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5ecd2a942ca3'
down_revision: Union[str, Sequence[str], None] = '0d3e2936f4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('zoom_account_id', sa.String(length=128), nullable=True),
    sa.Column('openemr_appointment_id', sa.String(length=128), nullable=True),
    sa.Column('openemr_encounter_number', sa.String(length=128), nullable=True),
    sa.Column('openemr_provider_id', sa.String(length=128), nullable=True),
    sa.Column('openemr_patient_id', sa.String(length=128), nullable=True),
    sa.Column('zoom_meeting_id', sa.String(length=128), nullable=True),
    sa.Column('zoom_note_id', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoom_accounts',
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=False), # type: ignore
    sa.Column('webhook_secret', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True), # type: ignore
    sa.Column('zoom_access_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True), # type: ignore
    sa.Column('zoom_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openemr_client_id', sa.String(length=256), nullable=True),
    sa.Column('openemr_client_secret', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True), # type: ignore
    sa.Column('openemr_registration_access_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True), # type: ignore
    sa.Column('openemr_registration_client_uri', sa.String(length=512), nullable=True),
    sa.Column('openemr_access_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True), # type: ignore
    sa.Column('openemr_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('private_key_path', sa.String(length=512), nullable=True),
    sa.Column('kid', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('demo_patient_override_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('demo_patient_email_override', sa.String(length=256), nullable=True),
    sa.Column('demo_patient_phone_override', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('appointment_type_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoom_account_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_type_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_type_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zoom_account_id'], ['zoom_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_type_filters_zoom_account_id'), 'appointment_type_filters', ['zoom_account_id'], unique=False)
    op.create_table('meeting_records',
    sa.Column('zoom_meeting_id', sa.String(length=128), nullable=False),
    sa.Column('zoom_account_id', sa.String(length=128), nullable=False),
    sa.Column('zoom_start_url', sa.String(length=1024), nullable=True),
    sa.Column('zoom_join_url', sa.String(length=1024), nullable=True),
    sa.Column('alternative_host_email', sa.String(length=256), nullable=True),
    sa.Column('openemr_appointment_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_provider_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_appt_status', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zoom_account_id'], ['zoom_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('zoom_meeting_id')
    )
    op.create_index(op.f('ix_meeting_records_zoom_account_id'), 'meeting_records', ['zoom_account_id'], unique=False)
    op.create_table('provider_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoom_account_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_fhir_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_provider_npi', sa.String(length=10), nullable=False),
    sa.Column('openemr_provider_id', sa.String(length=128), nullable=True),
    sa.Column('openemr_provider_name', sa.String(length=256), nullable=True),
    sa.Column('zoom_user_email', sa.String(length=256), nullable=False),
    sa.Column('zoom_user_name', sa.String(length=256), nullable=True),
    sa.Column('zoom_user_id', sa.String(length=128), nullable=True),
    sa.Column('zoom_user_type', sa.Integer(), nullable=True),
    sa.Column('default_alternative_host_email', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zoom_account_id'], ['zoom_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_mappings_zoom_account_id'), 'provider_mappings', ['zoom_account_id'], unique=False)
    op.create_table('clinical_note_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoom_meeting_id', sa.String(length=128), nullable=False),
    sa.Column('zoom_note_id', sa.String(length=128), nullable=False),
    sa.Column('zoom_note_title', sa.String(length=256), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('written_to_openemr_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_in_zoom_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_written_to_openemr', sa.Boolean(), nullable=False),
    sa.Column('is_completed_in_zoom', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['zoom_meeting_id'], ['meeting_records.zoom_meeting_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zoom_note_id')
    )
    op.create_index(op.f('ix_clinical_note_records_zoom_meeting_id'), 'clinical_note_records', ['zoom_meeting_id'], unique=False)
    op.create_table('meeting_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoom_meeting_id', sa.String(length=128), nullable=False),
    sa.Column('openemr_patient_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zoom_meeting_id'], ['meeting_records.zoom_meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_patients_zoom_meeting_id'), 'meeting_patients', ['zoom_meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_patients_zoom_meeting_id'), table_name='meeting_patients')
    op.drop_table('meeting_patients')
    op.drop_index(op.f('ix_clinical_note_records_zoom_meeting_id'), table_name='clinical_note_records')
    op.drop_table('clinical_note_records')
    op.drop_index(op.f('ix_provider_mappings_zoom_account_id'), table_name='provider_mappings')
    op.drop_table('provider_mappings')
    op.drop_index(op.f('ix_meeting_records_zoom_account_id'), table_name='meeting_records')
    op.drop_table('meeting_records')
    op.drop_index(op.f('ix_appointment_type_filters_zoom_account_id'), table_name='appointment_type_filters')
    op.drop_table('appointment_type_filters')
    op.drop_table('zoom_accounts')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
