"""add account_config table, move config fields from zoom_accounts

Revision ID: 77ba73f9eedb
Revises: 5ecd2a942ca3
Create Date: 2026-04-28 22:11:24.194194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ba73f9eedb'
down_revision: Union[str, Sequence[str], None] = '5ecd2a942ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_configs',
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/New_York', nullable=False),
    sa.Column('allow_shared_zoom_user', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('demo_patient_override_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('demo_patient_email_override', sa.String(length=256), nullable=True),
    sa.Column('demo_patient_phone_override', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['zoom_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.drop_column('zoom_accounts', 'timezone')
    op.drop_column('zoom_accounts', 'demo_patient_override_enabled')
    op.drop_column('zoom_accounts', 'demo_patient_email_override')
    op.drop_column('zoom_accounts', 'demo_patient_phone_override')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoom_accounts', sa.Column('demo_patient_phone_override', sa.VARCHAR(length=32), nullable=True))
    op.add_column('zoom_accounts', sa.Column('demo_patient_email_override', sa.VARCHAR(length=256), nullable=True))
    op.add_column('zoom_accounts', sa.Column('demo_patient_override_enabled', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('zoom_accounts', sa.Column('timezone', sa.VARCHAR(length=64), nullable=False))
    op.drop_table('account_configs')
    # ### end Alembic commands ###
