"""add note_writeback_mode to account_configs

Revision ID: 8e1a97239ec2
Revises: 18c6821766b3
Create Date: 2026-05-04 13:20:33.368022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1a97239ec2'
down_revision: Union[str, Sequence[str], None] = '18c6821766b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_configs', sa.Column('note_writeback_mode', sa.String(length=32), server_default='both', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_configs', 'note_writeback_mode')
    # ### end Alembic commands ###
