"""add openemr_provider_id to provider_mappings

Revision ID: bc1e2fb3b8be
Revises: 9f2c1a7d4b6e
Create Date: 2026-04-20 21:23:55.114941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1e2fb3b8be'
down_revision: Union[str, Sequence[str], None] = '9f2c1a7d4b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_mappings', sa.Column('openemr_provider_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_mappings', 'openemr_provider_id')
    # ### end Alembic commands ###
