"""split demo_patient_override_enabled into email and phone flags

Revision ID: d7de11bd0c97
Revises: 77ba73f9eedb
Create Date: 2026-04-29 10:09:47.211099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7de11bd0c97'
down_revision: Union[str, Sequence[str], None] = '77ba73f9eedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_configs', sa.Column('demo_patient_email_override_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('account_configs', sa.Column('demo_patient_phone_override_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('account_configs', 'demo_patient_override_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_configs', sa.Column('demo_patient_override_enabled', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    op.drop_column('account_configs', 'demo_patient_phone_override_enabled')
    op.drop_column('account_configs', 'demo_patient_email_override_enabled')
    # ### end Alembic commands ###
