"""Add Epic-ZCC config columns to AccountConfig + credentials to ZoomAccount (S11-02)

Sprint 11 schema for the Epic-style ZCC CTI middleware.

AccountConfig gains 8 columns (enable flag + 7 SE-supplied identifiers that
map to Zoom's Epic-integration admin-portal config screen).

ZoomAccount gains 2 columns: an Epic-style client_id (UUID format) and a
32-char hex KID — both generated by the "Initialize CTI" button in the
Epic ZCC tab. The KID is intentionally distinct from the existing
ZoomAccount.kid (which is used for OpenEMR SMART on FHIR private_key_jwt)
so the JKU URL Zoom registers is unambiguous. The same RSA keypair
(private_key_path) signs both flows.

All new columns except epic_zcc_enabled and epic_zcc_recipient_id_type
are nullable so existing rows survive without manual backfill. The
recipient_id_type defaults to "Phone" — Zoom's documented default for
the field across Epic integrations.

PHI is NOT stored on the Zoomly side. SSN-last-4 lookup (S11-05) queries
OpenEMR's patient_data.ss directly via get_openemr_db_engine().

Revision ID: db55813136ea
Revises: fadc607b7921
Create Date: 2026-06-09
"""
from alembic import op
import sqlalchemy as sa


revision = 'db55813136ea'
down_revision = 'fadc607b7921'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('zoom_accounts', sa.Column('epic_zcc_client_id', sa.String(length=64), nullable=True))
    op.add_column('zoom_accounts', sa.Column('epic_kid', sa.String(length=64), nullable=True))

    op.add_column('account_configs', sa.Column('epic_zcc_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('account_configs', sa.Column('epic_zcc_connection_name', sa.String(length=256), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_backend_url', sa.String(length=256), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_background_user_id', sa.String(length=128), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_background_user_id_type', sa.String(length=64), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_phone_system_id', sa.String(length=128), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_phone_system_id_type', sa.String(length=64), nullable=True))
    op.add_column('account_configs', sa.Column('epic_zcc_recipient_id_type', sa.String(length=64), nullable=False, server_default='Phone'))


def downgrade():
    op.drop_column('account_configs', 'epic_zcc_recipient_id_type')
    op.drop_column('account_configs', 'epic_zcc_phone_system_id_type')
    op.drop_column('account_configs', 'epic_zcc_phone_system_id')
    op.drop_column('account_configs', 'epic_zcc_background_user_id_type')
    op.drop_column('account_configs', 'epic_zcc_background_user_id')
    op.drop_column('account_configs', 'epic_zcc_backend_url')
    op.drop_column('account_configs', 'epic_zcc_connection_name')
    op.drop_column('account_configs', 'epic_zcc_enabled')
    op.drop_column('zoom_accounts', 'epic_kid')
    op.drop_column('zoom_accounts', 'epic_zcc_client_id')
